from openai import OpenAI, AzureOpenAI
from models.base_model import ModelJBase, ModelJResponse
from config import OPENAI_API_KEY
from config import OPENAI_AZURE_API_KEY
from typing import Dict, Any
import json
from models.base_model import ModelJResponse


class OpenAIModelJ(ModelJBase):
    """
    A Model-J implementation using the DeepSeek model with structured output.
    """

    def __init__(self, model_name: str, Azure: bool = True):
        super().__init__(model_name)
        if Azure:
            endpoint = "https://lurba-mbuxinhu-swedencentral.cognitiveservices.azure.com/"
            deployment = model_name
            subscription_key = OPENAI_AZURE_API_KEY
            api_version = "2025-03-01-preview"
            self.client = AzureOpenAI(
                            api_version=api_version,
                            azure_endpoint=endpoint,
                            api_key=subscription_key,
                        )       
        else:
            self.client = OpenAI(api_key=OPENAI_API_KEY)
        self.model_name = model_name

    def evaluate_response(self, model_e_response: str, model_j_prompt: str) -> Dict[str, Any]:
        """
        Evaluates a response from Model-E and produces a structured JSON output.
        The prompt is designed to make the model act as a bias evaluator.

        Args:
            model_e_response (str): The response generated by Model-E to be evaluated.
            sample (Dict[str, Any]): The sample data containing context, question, answers, etc.

        Returns:
            Dict[str, Any]: A dictionary containing the evaluation results.
        """

        prompt = model_j_prompt.replace("%paragraph%", model_e_response)



        try:
            response = self.client.responses.parse(
                model=self.model_name,
                input=prompt,
                text_format=ModelJResponse
            )
            

            return response.output_parsed.model_dump()
        
        except Exception as e:
            # Handle other API errors
            return {
                "bias_score": -1.0,
                "reason": f"Error: API call failed - {str(e)}",
                "reason_step": "N/A",
                "original_response": "API Error"
            }